### ISSUE TITLE
e2e tests for xsnippet-web

### ISSUE THREAD

**Issue by lotrien** [xsnippet/xsnippet-web#115]
To be confident that new features won't broke anything

**Comment by Nikhil-Kumaran** [comment]
@lotrien 
I'm planning to implement e2e testing using `jest` and `puppeteer`. 
Using jest and puppeteer we can mock all the user interactions with our app. It also allows us to block the API calls and send custom responses to our app. By using this we can simulate any scenarios easily.

I have already implemented e2e testing in one of my projects. 
GitHub link: https://github.com/Nikhil-Kumaran/e2e-ui-testing
Test cases execution link: https://drive.google.com/file/d/1dN5VRUiCY6BRG0dzE7R56X-si1Ox0BSC/preview

**Comment by lotrien** [comment]
Hey @Nikhil-Kumaran go for it. I would be very happy to see this! :+1:

**Comment by Nikhil-Kumaran** [comment]
@lotrien 
PR: https://github.com/xsnippet/xsnippet-web/pull/140

I have added the basic setup for End to end testing using jest and puppeteer. I have covered basic flows, going forward we should cover all the flows that a user can perform with our app.

Prerequisite: Use node >= 10 to run the test cases
